const mongoose = require('./connect');
var HOMESCHEMA = {
    satus               : String,
    oProperty           : Array,  // PROPIEDAD
    ID                  : Number,
    pk                  : Number,
    codigo              : String,
    idVendedor          : Number,
    codigoInmobiliaria  : String,
    STATUS              : String,
    idTipo              : Number,
    tipo                : String,
    oferta              : String,
    estado              : String,
    idCiudad            : Number,
    idTipoInmueble      : Number,
    region              : String,
    ubicacion           : String,
    zona                : String,
    idZona              : Number, //DATO IMPORTANTE
    direccion           : String,
    moneda              : String,
    monedaIso           : String,
    precio              : String,
    precioIso           : Number,
    descripcion         : String,
    fecentrega          : String,
    supterreno          : String,
    servicios           : Array, // PUEDEN SER MULTIPLES
    amurallado          : String,
    anioconstruccion    : String,
    desHabitacion       : String,
    desBano             : String,
    supconstruccion     : String,
    supterraza          : String,
    numDormitorios      : String,
    dormitorios         : String,
    numBanos            : String,
    banos               : String,
    piso                : String,
    elevador            : String,
    baulera             : String,
    piscina             : String,
    parqueos            : String,
    numParqueos         : String,
    amoblado            : String,
    fecpublicidad       : String,
    latitud             : String,
    longitud            : String,
    bshow               : Boolean,
    bmipublic           : Boolean,
    rating              : Number,
    href                : String,
    images              : Array,   // FOTOGRAFIAS DE CASA
    oContact            : Array,    // CONTACTO
    Cpk                 : Number,
    Cname               : String,
    lastname            : String,
    phone               : String,
    phoneFiltered       : String,
    phone2              : String,
    phone2Filtered      : String,
    movil               : String,
    movilFiltered       : String,
    movil2              : String,
    movil2Filtered      : String,
    email               : String,
    ciudad              : String,
    foto                : Array, // IMAGEN DEL CONTACTO
    phoneFirstDigits    : String
};
const HOME = mongoose.model("home",HOMESCHEMA);
module.exports = HOME;